version: "3.7"
services:
  backend:
    build: api
    secrets:
      - root-db-pw
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.25i
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=flask_users
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root-db-pw
    expose:
      - 3306
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on: 
      - backend
volumes:
  db-data:
secrets:
  root-db-pw:
          external: true
