version: "3.7"
services:
  backend:
    build: api
    depends_on:
        - db
    ports:
        - 5000:5000
    networks:
      - backnet
      - frontnet
    environment:
      - MYSQL_ROOT_PASSWORD=${root_db_pw}
  db:
    image: mysql:8.0.25
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=db-78n9n
    expose:
      - 3306
    networks:
      - backnet
volumes:
  db-data:
networks:
  backnet:
  frontnet:
